// Sentence-aligned content reviewed with the original text.
export const article01Reuse: Record<string, string> = {
  "It is possible to get an education at a university.": "It is _____ to _____.",
  "It has been done; not often, but the fact that a proportion, however small, of college students do get a start in interested, methodical study, proves my thesis, and the following personal experience I have to offer illustrates it and shows how to get around the faculty, the other students, and the whole college system of mind-fixing.": "The fact that _____ proves _____, and _____ illustrates _____ and shows how to _____.",
  "My method might lose a boy his degree, but a degree is not worth so much as the capacity and the drive to learn.": "_____ might _____, but _____ is not worth as much as _____.",
  "My method was hit on by accident and some instinct.": "_____ was discovered by _____.",
  "I specialized.": "I _____.",
  "With several courses prescribed, I concentrated on the one or two that interested me most and worked intensively on my favorites.": "With _____ done, I concentrated on _____ and _____.",
  "In my first two years, for example, I worked at English and political economy and read philosophy.": "In _____, for example, I _____ and _____.",
  "At the beginning of my junior year I had several cinches in history.": "At the beginning of _____, I had _____.",
  "Now I liked history; I had neglected it partly because I rebelled at the way it was taught, as positive knowledge unrelated to politics, art, life, or anything else.": "I liked _____; I had _____ partly because _____.",
  "The professors gave us chapters out of a few books to read and be quizzed on.": "_____ gave _____ something to _____ and be _____ on.",
  "Blessed as I was with a \"bad memory,\" I could not commit to it anything that I did not understand and intellectually need.": "Because I _____, I could not _____ anything that _____.",
  "The bare record of the story of man, with names, dates, and irrelative events, bored me.": "_____, with _____, bored me.",
  "But I had discovered in my readings of literature, philosophy, and political economy that history had light to throw upon unhistorical questions.": "I had discovered in _____ that _____.",
  "So I proposed in my junior and senior years to specialize in history, taking all the courses required and those also that I had failed.": "I planned to _____, taking _____.",
  "With this in mind I listened attentively to the first introductory talk of Professor William Cary Jones on American constitutional history.": "With this in mind, I _____.",
  "He was a dull lecturer, but I noticed that, after telling us what pages of what books we must be prepared in, he listed off some other references \"for those that may care to dig deeper.\"": "_____ was _____, but I noticed that, after _____, he _____.",
  "When the rest of the class rushed out into the sunshine, I went up to the professor and, to his surprise, asked for this memorandum.": "When _____, I _____ and, to his surprise, _____.",
  "He gave it to me.": "He gave _____ to _____.",
  "Up in the library I ran through the required chapters in the two different books, and they differed on several points.": "In _____, I _____, and _____.",
  "Turning to the other authorities, I saw that they disagreed on the same facts and also on others.": "Turning to _____, I saw that _____.",
  "The librarian, appealed to, helped me search the bookshelves till the library closed, and then I called on Professor Jones for more references.": "When I asked _____ for help, _____ helped me _____ until _____, and then I _____.",
  "He was astonished, invited me in, and began to approve my industry, which astonished me.": "He was _____, _____, and _____, which _____.",
  "I was not trying to be a good boy; I was better than that: I was a curious boy.": "I was not trying to _____; I was _____: I was _____.",
  "He lent me a couple of his books, and I went off to my club to read them.": "He _____, and I went off to _____ to _____.",
  "They only deepened the mystery, clearing up the historical question, but leaving the answer to be dug for and written.": "_____ clarified _____ but left _____ to be _____.",
  "The historians did not know!": "_____ did not _____!",
  "History was not a science, but a field for research, a field for me, for any young man, to explore, to make discoveries in and write a scientific report about.": "_____ was not _____ but _____, a field for _____ to explore and make discoveries in.",
  "I was fascinated.": "I was _____.",
  "As I went on from chapter to chapter, day after day, finding frequently essential differences of opinion and of fact, I saw more and more work to do.": "As I _____, _____, I _____.",
  "In this course, American constitutional history, I hunted far enough to suspect that the Fathers of the Republic who wrote our sacred Constitution of the United States not only did not, but did not want to, establish a democratic government, and I dreamed for a while—as I used as a child to play I was Napoleon or a trapper—I promised myself to write a true history of the making of the American Constitution.": "I began to suspect that _____ had not only failed to _____ but had also never intended to _____.",
  "I did not do it; that chapter has been done or well begun since by two men: Smith of the University of Washington and Beard of Columbia.": "I did not _____; _____ has since been _____ by _____.",
  "I found other events, men, and eras waiting for students.": "I found _____ waiting for _____.",
  "In all my other courses, in ancient, in European, and in modern history, the disagreeing authorities carried me back to the need of a fresh search for the original documents or other clinching evidence.": "In _____, _____ brought me back to the need for _____.",
  "Of course I did well in my classes.": "Of course I _____.",
  "The history professors soon knew me as a student and seldom put a question to me except when the class didn't know the answer.": "_____ soon _____ and seldom _____ except when _____.",
  "Then Professor Jones would say, \"Well, Steffens, tell them about it.\"": "Then _____ would say, “_____.”",
  "Fine.": "_____.",
  "But vanity wasn't my ruling passion then.": "But _____ wasn't _____ then.",
  "What I had was a quickening sense that I was learning a method of studying history and that every chapter of it, from the beginning of the world to the end, is crying out to be rewritten.": "What I had was _____ that _____ and that _____.",
  "There was something for Youth to do.": "There was something for _____ to do."
};
